name: Build Android

on: [push, pull_request]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install app dependencies
        working-directory: ./interface/
        run: npm install

      - name: Build Angular App
        working-directory: ./interface/
        run: npx ng build --configuration production

      - name: Sync Android
        working-directory: ./interface/
        run: npx cap sync android

      - name: Generate the Android App Bundle
        working-directory: ./interface/android/
        run: ./gradlew assembleDebug

      - name: Upload dev APK
        uses: actions/upload-artifact@v1
        with:
          name: app-dev
          path: ./interface/android/app/build/outputs/apk/debug/app-debug.apk
